modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/additional-structures/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:structure_block"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/AdditionalStructures_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/additional-structures"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Adds over 150 new structures to the game to enhance your world!'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    type="required"
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    type="required"
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"

