modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/additional-structures/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:structure_block"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Additional-Structures/refs/heads/master/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/additional-structures"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Adds over 150 new structures to the game to enhance your world!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/block/structure_block_data.png"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="magmacore"
    referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
    reason="Provides basic code and features such as update-checker"
    type="required"
    versionRange="${magmacore_version_range}"
    ordering="AFTER"
    side="BOTH"
